---
title: "Binomial-Quabbin-Stats"
author: "Abby Robinson"
date: "1/11/2022"
output: html_document
---

```{r}
library(curl)
```

Now lets load the **Count Data** into our markdown file using the {curl} command 

```{r}
c <- curl("https://raw.githubusercontent.com/butterfliesrcool/Quabbin_Data/main/learning-phase-transect-one.csv")
l1  <- read.csv(c, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(l1) #we can use the head function to view the first 10 rows in the dataset 
length(l1$attacks)
sum(l1$attacks)
```

```{r}
t1 <- rep(1, each=4000)
l1$transect <- t1
head(l1)
```

```{r}
r <- curl("https://raw.githubusercontent.com/butterfliesrcool/Quabbin_Data/main/learning-phase-transect-two.csv")
l2  <- read.csv(r, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(l2) #we can use the head function to view the first 10 rows in the dataset 
length(l2$attacks)
sum(l2$attacks)
```

```{r}
t2 <- rep(2, each=4000)
l2$transect <- t2
head(l2)
```

```{r}
p <- curl("https://raw.githubusercontent.com/butterfliesrcool/Quabbin_Data/main/learning-phase-transect-three.csv")
l3  <- read.csv(p, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(l3) #we can use the head function to view the first 10 rows in the dataset 
length(l3$attacks)
sum(l3$attacks)
```

```{r}
t3 <- rep(3, each=4000)
l3$transect <- t3
head(l3)
```

```{r}
learning <- rbind(l1, l2, l3)
length(learning$attacks)
sum(learning$attacks)
```

```{r}
no.zero.learning <- subset(learning, attacks == "1", drop = FALSE)
table(no.zero.learning$attacks, no.zero.learning$species)
chisq.test(table(no.zero.learning$attacks, no.zero.learning$species))
```

```{r}
lb <- subset(no.zero.learning, species == "battus", drop = FALSE)
table(lb$attacks, lb$day)
chisq.test(table(lb$attacks, lb$day))
```

```{r}
lj <- subset(no.zero.learning, species == "junonia", drop = FALSE)
table(lj$attacks, lj$day)
chisq.test(table(lj$attacks, lj$day))
```

```{r}
glm <- glm(data = learning, attacks ~ species + day, family = "poisson")
summary(glm)
confint(glm)
```

```{r}
b <- subset(learning, species == "battus", drop = FALSE)
glm <- glm(data = b, attacks ~ day, family = "poisson")
summary(glm)
confint(glm)
```

```{r}
j <- subset(learning, species == "junonia", drop = FALSE)
glm <- glm(data = j, attacks ~ day, family = "poisson")
summary(glm)
confint(glm)
```

```{r}
library(survival)
library(survminer)
library(ggplot2)
```
```{r}
model <- survfit(Surv(day, day+1, attacks) ~ species, data=learning)
model
summary(model)
```

```{r}
p <- ggsurvplot(fit = model,
           xaxt = "n",
           xlab="Time (days)", 
           ylab="Survivorship",
           ylim = c(0.97, 1.0), 
           xlim = c(1, 5),  
           data = learning, 
           axes = FALSE, 
           linetype = 1,
           legend.title = "Species")

p$plot <- p$plot + theme_minimal()
p$plot <- p$plot + theme_classic()

##rename the x axis values 
p$plot <- p$plot + scale_x_continuous(breaks = c(1,2,3,4,5), labels = c(0,1,2,3,4))

p$plot <- p$plot + scale_color_manual(values = c("darkblue", "sienna4"))

p$plot
```

```{r}
a <- curl("https://raw.githubusercontent.com/butterfliesrcool/Quabbin_Data/main/testing-phase-transect-one.csv")
te1  <- read.csv(a, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(t1) #we can use the head function to view the first 10 rows in the dataset 
length(t1$attacks)
sum(t1$attacks)
```

```{r}
tt1 <- rep(1, each=4000)
t1$transect <- tt1
head(t1)
```
